// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuHVkDpoT386kNDjOunflcRMCROyZ_iZo',
    appId: '1:1019725412490:web:12b623de3cc9bdc1619573',
    messagingSenderId: '1019725412490',
    projectId: 'flutter-chat-app-b024c',
    authDomain: 'flutter-chat-app-b024c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b024c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11uQX7nHDb56Kr-oa4lP9mz2RSeucVko',
    appId: '1:1019725412490:android:2787d2f07672a2eb619573',
    messagingSenderId: '1019725412490',
    projectId: 'flutter-chat-app-b024c',
    storageBucket: 'flutter-chat-app-b024c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCXmjz55_XfaIvdyUj51xhxIbXJVn3e_A',
    appId: '1:1019725412490:ios:f2a0073791dc31d4619573',
    messagingSenderId: '1019725412490',
    projectId: 'flutter-chat-app-b024c',
    storageBucket: 'flutter-chat-app-b024c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCXmjz55_XfaIvdyUj51xhxIbXJVn3e_A',
    appId: '1:1019725412490:ios:f2a0073791dc31d4619573',
    messagingSenderId: '1019725412490',
    projectId: 'flutter-chat-app-b024c',
    storageBucket: 'flutter-chat-app-b024c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuHVkDpoT386kNDjOunflcRMCROyZ_iZo',
    appId: '1:1019725412490:web:b5bb4064b5b55f01619573',
    messagingSenderId: '1019725412490',
    projectId: 'flutter-chat-app-b024c',
    authDomain: 'flutter-chat-app-b024c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b024c.appspot.com',
  );
}
